---
# Oracle Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: oracle-db-secret
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # echo -n 'your-username' | base64
  username: <base64-encoded-username>
  # echo -n 'your-password' | base64
  password: <base64-encoded-password>
  # echo -n 'jdbc:oracle:thin:@your-adb-service?TNS_ADMIN=/app/wallet' | base64
  db-url: <base64-encoded-db-url>

---
# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # echo -n 'your-secure-jwt-secret' | base64
  jwt-secret: <base64-encoded-jwt-secret>

---
# Oracle Wallet Files Secret
# Create this from your wallet zip file
apiVersion: v1
kind: Secret
metadata:
  name: oracle-wallet-secret
type: Opaque
data:
  # Convert each wallet file to base64
  # cat cwallet.sso | base64 -w 0
  cwallet.sso: <base64-encoded-cwallet.sso>
  # cat ewallet.p12 | base64 -w 0
  ewallet.p12: <base64-encoded-ewallet.p12>
  # cat keystore.jks | base64 -w 0
  keystore.jks: <base64-encoded-keystore.jks>
  # cat ojdbc.properties | base64 -w 0
  ojdbc.properties: <base64-encoded-ojdbc.properties>
  # cat sqlnet.ora | base64 -w 0
  sqlnet.ora: <base64-encoded-sqlnet.ora>
  # cat tnsnames.ora | base64 -w 0
  tnsnames.ora: <base64-encoded-tnsnames.ora>
  # cat truststore.jks | base64 -w 0
  truststore.jks: <base64-encoded-truststore.jks>